# -*- coding: utf-8 -*-
"""EX_Forest_random (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imvir1KLe3d1nugVOlsJwO58MFvvRhQt

# Ramdom Forest (Text)
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import pickle
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd

with open('base.pkl', mode= 'rb') as f:
  x_base_treinamento, y_base_treinamemto, x_base_teste, y_base_teste = pickle.load(f)

x_base_teste.shape, y_base_teste.shape

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')  # ou 'median'
x_base_treinamento = imputer.fit_transform(x_base_treinamento)

ramdom_forest_base = RandomForestClassifier(n_estimators=40, criterion='entropy', random_state=0)
ramdom_forest_base.fit(x_base_treinamento, y_base_treinamemto)

previsoes = ramdom_forest_base.predict(x_base_teste)
previsoes

y_base_teste

from sklearn.metrics import accuracy_score, classification_report
accuracy_score(y_base_teste, previsoes)

print(classification_report(y_base_teste,previsoes))